#主機host
myHost: 34.44.233.80
#127.0.0.1
#192.168.98.86

#靜態圖片位置
imagePath: /tmp/images/
#C:/git-repository/project-store-backend/springboot-store/images/

#server配置
server:
  port: 8002
  servlet:
    context-path: /

#連接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://34.44.233.80:3306/shop_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#redis配置
  data:
    redis:
      host: 34.44.233.80
      port: 6379

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.shop.pojo
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto  #主鍵自增長

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效時間，單位分鐘
    tokenSignKey: springproject666 #自定義密鑰